apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tradelab-dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: ghcr.io/aidun/tradelab-backend
    newTag: latest
  - name: ghcr.io/aidun/tradelab-frontend
    newTag: latest

patches:
  - path: patch-ingress.yaml
