apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tradelab-dev

resources:
  - ../../base
  - namespace.yaml

secretGenerator:
  - name: tradelab-database
    envs:
      - .env.database

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: patch-ingress.yaml
