apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - database-bootstrap-script-configmap.yaml
  - database-bootstrap-rbac.yaml
  - database-bootstrap-job.yaml
  - backend-configmap.yaml
  - frontend-configmap.yaml
  - postgres-persistent-volume-claim.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - backend-service.yaml
  - backend-deployment.yaml
  - frontend-service.yaml
  - frontend-deployment.yaml
  - ingress.yaml
