apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tradelab

resources:
  - ../../base
  - ingress-frontend-entrypoint.yaml
  - ingress-backend-entrypoint.yaml
  - middleware-strip-prefix.yaml

patches:
  - path: patch-backend-deployment.yaml
  - path: patch-frontend-deployment.yaml
  - path: patch-frontend-configmap.yaml
  - path: patch-ingress-delete.yaml
  - path: patch-postgres-persistent-volume-claim.yaml
