apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tradelab-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/aidun/tradelab.git
    targetRevision: v0.1.22
    path: deploy/kubernetes/overlays/production
    kustomize:
      images:
        - ghcr.io/aidun/tradelab-backend:v0.1.22
        - ghcr.io/aidun/tradelab-frontend:v0.1.22
  destination:
    server: https://kubernetes.default.svc
    namespace: tradelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
