apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tradelab-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/aidun/tradelab.git
    targetRevision: 1468b8e488b4090913ae3ddaef9cc1edd6c9431d
    path: deploy/kubernetes/overlays/development
    kustomize:
      images:
        - ghcr.io/aidun/tradelab-backend:master-1468b8e488b4
        - ghcr.io/aidun/tradelab-frontend:master-1468b8e488b4
  destination:
    server: https://kubernetes.default.svc
    namespace: tradelab-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
