apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tradelab-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/aidun/tradelab.git
    targetRevision: aa4f3723df1f65df42222dcbeded6f75a65de985
    path: deploy/kubernetes/overlays/development
    kustomize:
      images:
        - ghcr.io/aidun/tradelab-backend:master-aa4f3723df1f
        - ghcr.io/aidun/tradelab-frontend:master-aa4f3723df1f
  destination:
    server: https://kubernetes.default.svc
    namespace: tradelab-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
