apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 34.2.0
    helm:
      releaseName: traefik
      values: |
        ingressClass:
          enabled: true
          isDefaultClass: true
          name: traefik
        ingressRoute:
          dashboard:
            enabled: false
        service:
          type: LoadBalancer
          annotations:
            metallb.io/loadBalancerIPs: 192.168.2.200
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
